import { Nunito, Varela_Round,  } from "next/font/google";
import styles from '../components/css/privacypolicy.module.css'

// const nunito = Nunito({
// 	weight: "400",
// 	subsets: ["latin"],
// 	display: "swap",
// 	adjustFontFallback: false,
// });

const varela_round = Varela_Round({
		weight: "400",
		subsets: ["latin"],
		display: "swap",
		variable: '--font-varela'
})

const PrivacyPolicyPage = () => {
	return (
		<main className={`${styles.main} ${varela_round.variable}`}>
			<h2>Privacy Policy</h2>
		<p>
			Engineering Career Expo ("we," "our," or "us") is committed to
			protecting your privacy. This Privacy Policy explains how your personal
			information is collected, used, and disclosed by Engineering Career
			Expo.
		</p>
		<p>
			This Privacy Policy applies to our website, engcareerexpo.com , and its
			associated subdomains (collectively, our "Service"). By accessing or
			using our Service, you signify that you have read, understood, and agree
			to our collection, storage, use, and disclosure of your personal
			information as described in this Privacy Policy and our Terms of
			Service.
		</p>
		<h3>Privacy Principles</h3>
			<p>We follow the following principles in order to protect your privacy:</p>
			<ul>
				<li>We only use your personal data for the purposes we specify in this Privacy Notice, unless you agree otherwise;</li>
				<li>We do not keep your personal data if it is no longer needed; and</li>
				<li>Other than as we specify in this Privacy Notice, we do not share your personal data with third partie</li>
			</ul>

			<h3>Definitions and key terms</h3>
			<p>
				To help explain things as clearly as possible in this Privacy Policy,
				every time any of these terms are referenced, are strictly defined as:
			</p>

			<ul>
				<li>
					<b>Cookie:</b> small amount of data generated by a website and saved
					by your web browser. It is used to identify your browser, provide
					analytics, remember information about you such as your language
					preference or login information.
				</li>
				<li>
					<b>Company:</b> when this policy mentions “Company,” “we,” “us, or
					“our,” it refers to Engineering Career Expo, Faculty of Engineering,
					University of Lagos that is responsible for your information under
					this Privacy Policy. Country: where Engineering Career Expo or the
					owners/founders of Engineering Career Expo are based, in this case is
					Nigeria.
				</li>
				<li>
					<b>Customer:</b> refers to the company, organization or person that
					signs up to use the Engineering Career Expo Service to manage the
					relationships with your consumers or service users.
				</li>
				<li>
					<b>Device:</b> any internet connected device such as a phone, tablet,
					computer or any other device that can be used to visit Engineering
					Career Expo and use the services.
				</li>
				<li>
					<b>IP address:</b> Every device connected to the Internet is assigned
					a number known as an Internet protocol (IP) address. These numbers are
					usually assigned in geographic blocks. An IP address can often be used
					to identify the location from which a device is connecting to the
					Internet.
				</li>
				<li>
					<b>Personnel:</b> refers to those individuals who are employed by
					Engineering Career Expo or are under contract to perform a service on
					behalf of one of the parties.
				</li>
				<li>
					<b>Personal Data:</b> any information that directly, indirectly, or in
					connection with other information — including a personal
					identification number — allows for the identification or
					identifiability of a natural person.
				</li>
				<li>
					<b>Service:</b> refers to the service provided by Engineering Career
					Expo as described in the relative terms (if available) and on this
					platform.
				</li>
				<li>
					<b>Third-party service:</b> refers to advertisers, contest sponsors,
					promotional and marketing partners, and others who provide our content
					or whose products or services we think may interest you.
				</li>
				<li>
					<b>Website:</b> Engineering Career Expo’s site, which can be accessed
					via this URL: engcareerexpo.com.
				</li>
				<li>
					<b>You:</b> a person or entity that is registered with Engineering Career Expo to use the Services
				</li>
			</ul>

			<h3>What Information Do We Collect?</h3>
			<p>
				We collect information from you when you visit our service, register,
				place an order, subscribe to our newsletter, respond to a survey or fill
				out a form.
			</p>

			<ul>
				<li>Name / Username</li>
				<li>Phone Numbers</li>
				<li>Email Addresses</li>
			</ul>

				<h3>Recipients of Personal Data</h3>
				<p>We do not rent or sell your personal data to third parties, and will disclose it only in the following ways:</p>
				<ul>
					<li>To our third party service providers, as reasonably necessary for the uses described in this Privacy Notice. We ask our service providers to limit their use of personal data, and require them to agree to protect your personal data under written agreements;</li>
					<li>To our third party service providers, as reasonably necessary for the uses described in this Privacy Notice. We ask our service providers to limit their use of personal data, and require them to agree to protect your personal data under written agreements;</li>
					<li>To other organisations with which we run joint programs;</li>
					<li>With any potential acquirer, successor or assignee as part of a reorganisation, merger, sale, joint venture, assignment, transfer or other disposition of all or any portion of our business or assets;</li>
					<li>As required or permitted by applicable law, if we believe that such disclosure is (a) reasonably necessary to comply with legal process and law enforcement instructions and orders, such as a search warrant, subpoena, statute, judicial proceeding, or other legal process served on us, (b) helpful to prevent, investigate, or identify possible wrongdoing in connection with our Services, (c) helpful to protect our rights, reputation, property, or that of our students, visitors, users, corporate affiliates, or the public, or (d) to enforce compliance with our agreements with you; and
					</li>
					<li>As otherwise authorised by you.</li>
				</ul>
				<h3>Personal Data Obtained from Third Partie</h3>
				<p>We may obtain certain Personal Data about you from third party sources, which we may use for the purposes and in the ways described in “Collection of Information” and “Purposes for Processing Personal Data” above. In some cases, we may obtain your consent for additional uses.
			</p>
			<p>
			Single Sign-On: Some of our online services or research activities may allow you to register and login to those services through a third-party platform. When you login to our service through a third-party platform, you allow us to access and collect any personal data from your third-party platform account permitted under the settings and privacy statement of that platform.
			</p>
			<p>
			Supplemental Personal Data: We may receive additional personal data from third-party sources, such as public or private databases (for example, compilations of email or postal addresses), or companies or institutions that may sponsor or facilitate your participation in one of our programs, which we may also append to existing personal data.
			</p>
			<h3>Cookies</h3>
			<p>We use cookies in connection with your use of the Sites. A cookie is a small data file that is placed on your device when you visit a website. Cookies are widely used in order to make websites work or to work more efficiently, as well as to provide reporting information. A cookie may have unique identifiers and reside, among other places, on your device, in emails we send to you, and on the Site Some cookies are necessary for the website to function properly. They are usually only set in response to actions made by you which amount to a request for services, such as setting your privacy preferences, logging-in, or filling-in forms. You can set your browser to block or alert you about these cookies, but some parts of the site may not work if you block these cookies</p>
			<p>Our website also uses cookies during your on-line session for certain legitimate business interests, which may include delivering content specific to your interests, collecting the domain name of the server from which you are visiting, and providing us with information about the site’s performance. Our cookies enable us to relate your use of the site to information that you have specifically and knowingly provided to our website. If you do not allow these cookies, the site may be less user-friendly.</p>
			<h3>Security</h3>
			<p>The security of your personal data is important to us. We have adopted generally accepted industry standards in connection with our data collection, storage, and processing practices and security measures to protect against unauthorized access, alteration, disclosure, or destruction of your personal data, username, password, transaction information, and data stored on the Sites. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, while we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security.</p>
			<h3>Data Retention</h3>
			<p>We will retain your personal data only for so long as is necessary for the purpose for which it was collected, or as otherwise required or permitted by law. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalise it so that we can't identify you.
</p>
			<h3>How Do We Use The Information We Collect?</h3>
			<p>
				Any of the information we collect from you may be used in one of the
				following ways:
			</p>
			<ul>
				<li>To authenticate users to use our website</li>
				<li>
					To personalise your experience (your information helps us to better
					respond to your individual needs)
				</li>
				<li>
					To improve our service (we continually strive to improve our service
					offerings based on the information and feedback we receive from you)
				</li>
				<li>To process transactions</li>
				<li>
					To administer a contest, promotion, survey or other site feature To
					send periodic emails
				</li>
			</ul>

			<h3>
				Where and when is information collected from customers and end users?
			</h3>
			<p>
				We will collect personal information that you submit to us. We may also
				receive personal information about you from third parties as described
				above.
			</p>

			<h3>How Do We Use Your Email Address?</h3>
			<p>
				By submitting your email address on our service, you agree to receive
				emails from us. You can cancel your participation in any of these email
				lists at any time by clicking on the opt-out link or other unsubscribe
				option that is included in the respective email. We only send emails to
				people who have authorised us to contact them, either directly, or
				through a third party. We do not send unsolicited commercial emails,
				because we hate spam as much as you do. Email addresses submitted only
				through registering for one of our training programs will be used for
				the sole purpose of sending you information and updates pertaining to
				the training you registered for. If, however, you have provided the same
				email to us through another method, we may use it for any of the
				purposes stated in this Policy. Note: If at any time you would like to
				unsubscribe from receiving future emails, we include detailed
				unsubscribe instructions at the bottom of each email.
			</p>
			<h3>Could my information be transferred to other countries?</h3>
			<p>
					We are primarily incorporated in Nigeria and we won’t be transferring your personal information to other countries.
			</p>
			<h3>Is the information collected through our service secure?</h3>
			<p>
			We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorised access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.
			</p>
			<h3>Can I update or correct my information?</h3>
			<p>
				The rights you have to request updates or corrections to the information
				we collect depend on your relationship with us. Personnel may update or
				correct their information as detailed in our internal company employment
				policies. Customers have the right to request the restriction of certain
				uses and disclosures of personally identifiable information as follows.
				You can contact us in order to (1) update or correct your personally
				identifiable information, (2) change your preferences with respect to
				communications and other information you receive from us, or (3) delete
				the personally identifiable information maintained about you on our
				systems (subject to the following paragraph), by cancelling your
				account. Such updates, corrections, changes and deletions will have no
				effect on other information that we maintain, or information that we
				have provided to third parties in accordance with this Privacy Policy
				prior to such update, correction, change or deletion. To protect your
				privacy and security, we may take reasonable steps (such as requesting a
				unique password) to verify your identity before granting you profile
				access or making corrections. You are responsible for maintaining the
				secrecy of your unique password and account information at all times.
				You should be aware that it is not technologically possible to remove
				each and every record of the information you have provided to us from
				our system. The need to back up our systems to protect information from
				inadvertent loss means that a copy of your information may exist in a
				non-erasable form that will be difficult or impossible for us to locate.
				Promptly after receiving your request, all personal information stored
				in databases we actively use, and other readily searchable media will be
				updated, corrected, changed or deleted, as appropriate, as soon as and
				to the extent reasonably and technically practicable. If you are an end
				user and wish to update, delete, or receive any information we have
				about you, you may do so by contacting the organisation of which you are
				a customer.
			</p>
			<h3>Affiliates</h3>
			<p>
				If you are one of our workers or applicants, we collect information you
				voluntarily provide to us. We use the information collected for Human
				Resources purposes in order to administer benefits to workers and screen
				applicants. You may contact us in order to (1) update or correct your
				information, (2) change your preferences with respect to communications
				and other information you receive from us, or (3) receive a record of
				the information we have relating to you. Such updates, corrections,
				changes and deletions will have no effect on other information that we
				maintain, or information that we have provided to third parties in
				accordance with this Privacy Policy prior to such update, correction,
				change or deletion.
			</p>
			<h3>Sale of Business</h3>
			<p>
				We reserve the right to transfer information to a third party in the
				event of a sale, merger or other transfer of all or substantially all of
				the assets of us or any of its Corporate Affiliates (as defined herein),
				or that portion of us or any of its Corporate Affiliates to which the
				Service relates, or in the event that we discontinue our business or
				file a petition or have filed against us a petition in bankruptcy,
				reorganization or similar proceeding, provided that the third party
				agrees to adhere to the terms of this Privacy Policy.
			</p>
			<h3>Affiliates</h3>
			<p>
			We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with us, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
			</p>
			<h3>How Do We Protect Your Information?</h3>
			<p>
				We keep your information only so long as we need it to provide service
				to you and fulfil the purposes described in this policy. This is also
				the case for anyone that we share your information with and who carries
				out services on our behalf. When we no longer need to use your
				information and there is no need for us to keep it to comply with our
				legal or regulatory obligations, we'll either remove it from our systems
				or depersonalise it so that we can't identify you.
			</p>
			<h3>How Do We Protect Your Information?</h3>
			<p>
				We implement a variety of security measures to maintain the safety of
				your personal information when you place an order or enter, submit, or
				access your personal information. We offer the use of a secure server.
				All supplied sensitive/credit information is transmitted via Secure
				Socket Layer (SSL) technology and then encrypted into our Payment
				gateway providers database only to be accessible by those authorised
				with special access rights to such systems, and are required to keep the
				information confidential. After a transaction, your private information
				(credit cards, social security numbers, financials, etc.) is never kept
				on file. We cannot, however, ensure or warrant the absolute security of
				any information you transmit to us or guarantee that your information on
				the Service may not be accessed, disclosed, altered, or destroyed by a
				breach of any of our physical, technical, or managerial safeguards.
			</p>
			
			<h3>Governing Law</h3>
			<p>
				The laws of Nigeria, excluding its conflicts of law rules, shall govern
				this Agreement and your use of our service. Your use of our service may
				also be subject to other local, state, national, or international laws.
			</p>
			<h3>Your Consent</h3>
			<p>
				By using our service, registering an account, or making a purchase, you
				consent to this Privacy Policy.
			</p>
			<h3>Changes To Our Privacy Policy</h3>
			<p>
			If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.	This Privacy Policy applies only to the Services. The Services may
				contain links to other websites not operated or controlled by us. We are
				not responsible for the content, accuracy or opinions expressed in such
				websites, and such websites are not investigated, monitored or checked
				for accuracy or completeness by us. Please remember that when you use a
				link to go from the Services to another website, our Privacy Policy is
				no longer in effect. Your browsing and interaction on any other website,
				including those that have a link on our platform, is subject to that
				website’s own rules and policies. Such third parties may use their own
				cookies or other methods to collect information about you.
			</p>
			<h3>Changes To Our Privacy Policy</h3>
			<p>
				If we decide to change our privacy policy, we will post those changes on
				this page, and/or update the Privacy Policy modification date below.
			</p>
			<h3>Third-Party Services</h3>
			<p>
				We may display, include or make available third-party content (including
				data, information, applications and other products services) or provide
				links to third-party websites or services ("Third- Party Services"). You
				acknowledge and agree that we shall not be responsible for any
				Third-Party Services, including their accuracy, completeness,
				timeliness, validity, copyright compliance, legality, decency, quality
				or any other aspect thereof. We do not assume and shall not have any
				liability or responsibility to you or any other person or entity for any
				Third- Party Services. Third-Party Services and links thereto are
				provided solely as a convenience to you and you access and use them
				entirely at your own risk and subject to such third parties' terms and
				conditions.
			</p>
			<h3>Contact Us</h3>
			<p>Don't hesitate to contact us if you have any questions. Via Email: ecxunilag@gmail.com</p>
		</main>
	);
}

export default PrivacyPolicyPage;
